FriendModule.controller('FriendController', ['FriendService','$scope','$rootScope','$location','$routeParams',function(FriendService,$scope,$rootScope,$location,$routeParams){
	var me=this;
	me.searchUser=$routeParams.user;
	me.currentUser=$rootScope.currentUser;
	console.log(me.searchUser);
	me.showList=true;
	me.showRequests=false;
	me.showMyRequests=false;
	me.fetchUsers=function(){
		console.log('fetchUsers');
		FriendService.getUsers()
		.then(
			function(data)
			{
				me.users=data;
				console.log(me.users);
			},
			function(error)
			{
				alert('No matching record found');
			}
			)

	}

	me.sendRequest=function(user)
	{
		console.log('sendRequest');
		friendReq={
			user:me.currentUser,
			friend:user};
			FriendService.sendRequest(friendReq)
			.then(
				function(response)
				{
					console.log(response);
					if(response.status==200)
						alert("Request has been sent sucessfully!!")
				},
				function(error){
					alert('Error could not sucessfully sent request');
				}
				)
		}

		me.getFrndRequest=function()
		{
			console.log('getFrndRequest');
			FriendService.getMyRequests($rootScope.currentUser)
			.then(
				function(data)
				{
					me.requestList=data;
					console.log(me.requestList);
					me.showList=false;
					me.showRequests=true;
					me.showMyRequests=false;
				},
				function(error){
					alert(error);
				}
				)	
		}
		me.confirmRequest=function(frndData)
		{
			frndData.status='confirm';
			FriendService.confirmRequest(frndData)
			.then(
				function(data)
				{
					me.getFriends();
				},
				function(error){
					alert('Failed to reply the friend request');
				}
				)	
		}
		me.rejectRequest=function(frndData)
		{
			frndData.status='reject';
			FriendService.rejectRequest(frndData)
			.then(
				function(data)
				{
					alert(data);

				},
				function(error){
					alert('Failed to reply the friend request');
				}
				)	
		}
		me.deleteRequest=function(frndData)
		{
			console.log(frndData);
			FriendService.deleteRequest(frndData.friendId)
			.then(
				function(data)
				{
					me.getFriends();	
				},
				function(error){
					alert(error);
				}
				)	
		}
		me.getFriends=function()
		{
			FriendService.getFriends($rootScope.currentUser.userId)
			.then(
				function(data)
				{
					console.log(data);
					me.frndList=data;
					me.showList=true;
					me.showRequests=false;
					me.showMyRequests=false;
				},
				function(error){
					alert(error);
				}
				)	
		}
		me.getSentRequest=function(){
			console.log('getFrndRequest');
			FriendService.getSentRequests($rootScope.currentUser)
			.then(
				function(data)
				{
					me.sentList=data;
					console.log(me.requestList);
					me.showList=false;
					me.showRequests=false;
					me.showMyRequests=true;
				},
				function(error){
					alert(error);
				}
				)	
		}
	}])